---
- hosts: all
  remote_user: root
  tasks:
  - name: install percona repo
    yum: name=https://www.percona.com/redir/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present
  - name: install xtrabackup
    yum: name=xtrabackup state=latest
  - name: install deppends
    yum: name=qpress state=latest
  - name: install mail
    yum: name=qpress state=latest
  - name: install cron
    yum: name=mailx state=latest
  - name: copy backup script
    copy: src=/srv/xtrabackup/backupdbs dest=/root/backupdbs mode=0755
    become: yes
  - name: Creates backups directory
    file: path=/home/back-mysql state=directory
    become: yes
  - cron: name="mysql backup" minute="10" hour="21" job="/root/backupdbs"
    become: yes

